services:
  postgres:
    image: postgres:17-alpine
    container_name: medical-appointments-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: medical_user
      POSTGRES_PASSWORD: medical_password
      POSTGRES_DB: medical_appointments

    ports:
      - "5432:5432"

    volumes:
      - medical_appointments_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U medical_user -d medical_appointments"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  medical_appointments_data: